spring.datasource.url=jdbc:mysql://localhost:3306/astroganit?serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=false
springfox.documentation.enabled=true
springfox.documentation.swagger-ui.base-url=/ganitastro/auth/api/v99
razorpay.key_id=rzp_test_RWYEYoA0OKuXXq
razorpay.key_secret=o3ECB0mGM1wpf064lFfsAyrA
razorpay.webhook.secret=astroganit_webhook_secret_2025
